#31 - fixed control character regex stripping out valid characters
braintree/sanitize-url pull request #32
Opened 2021-03-12 16:12 UTC by akirchmyer

2021-03-15 15:56 UTC, crookedneighbor approved these changes
This looks reasonable to me.

2021-03-16 18:13 UTC, crookedneighbor commented
Want to do some final testing with the modules we maintain that consume sanitize-url. Hoping to get this merged an published this week.

2021-04-12 17:27 UTC, akirchmyer commented
@crookedneighbor any update on this?

2021-04-20 12:05 UTC, hugohaggmark commented
@crookedneighbor any update when this will be merged and release? Thank you.

2021-04-20 17:02 UTC, crookedneighbor commented
Sorry for the long wait, will try to give this my attention today.

2021-04-21 15:07 UTC, crookedneighbor requested changes

2021-04-21 15:07 UTC, crookedneighbor commented on src/index.ts
> +const ctrlCharactersRegex = /[\u0000-\u001F\u007F-\u009F]/gim;
Taking a look at this again, and I'm a little worried about one thing.

The regex we had previously works by only allowing certain characters to be used and excluding all others. That has the obvious problem of blocking out the particular characters you want to allow.

Your proposal instead just blocks the specific unicode characters that represent some hidden characters, but also _allows_ any character not in that range. It's possible that this is safe, but my knowledge of unicode character ranges is not expansive, and I'd feel more confident in this solution if we went back to allowing ranges.

The point of this check is to prevent `javascript:` and `data:` protocol urls from coming through when they have a hidden ctrl character in them that the browser ignores. So my worry is that either there is another set of hidden characters somewhere in the unicode range that could still be injected, or that sometime in the future additional unicode characters could be added that would not be caught by this regex.

So, can we instead just increase the range of characters we accept? That doesn't solve the problem holistically, as there will likely be other character ranges that should be acceptable, but I'd rather add those as they come in rather than opening the module up to an exploitation.

Again though, my unicode knowledge is not expansive, so if you can explain why just targeting this range  is safe for this module, I'm happy to have my opinion changed.

2021-04-28 22:03 UTC, gesa approved these changes
control character regex looks good! :shipit:

2021-04-29 15:54 UTC, crookedneighbor commented
If it's good enough for @gesa, it's good enough for me.

2021-04-29 15:54 UTC, merged