Vitest
braintree/sanitize-url pull request #59
Opened 2023-07-28 19:15 UTC by oscarleonnogales

2023-07-31 15:03 UTC, hollabaq86 requested changes
overall looks good. While we're here, let's add a section to the README detailing how to run tests and whether lint checks are included in that

2023-07-31 15:07 UTC, hollabaq86 commented
one other note: do we need to add `coverage` to any ignore files?

2023-07-31 18:37 UTC, oscarleonnogales commented
Made the requested changes 😄

2023-08-01 18:36 UTC, jplukarski approved these changes

2023-08-01 18:38 UTC, merged