Update dependencies
braintree/sanitize-url pull request #62
Opened 2023-08-21 20:34 UTC by oscarleonnogales

## Summary

* Created `constants.ts` file and moved constants definitions.
* Updated dependencies (all minor updates except for TypeScript, which was upgraded to the next major version)

For internal tracking -> 2912

2023-08-28 18:24 UTC, jplukarski approved these changes

2023-08-28 18:27 UTC, jplukarski requested changes
Looks like tests are failing because the unit tests are not pointing to the public NPM registry. You'll have to look at the package-lock and amend any package not pointing to the correct registry @oscarleonnogales .

2023-08-30 20:22 UTC, oscarleonnogales commented
> Looks like tests are failing because the unit tests are not pointing to the public NPM registry. You'll have to look at the package-lock and amend any package not pointing to the correct registry @oscarleonnogales .

Done!

2023-08-30 20:27 UTC, jplukarski approved these changes

2023-08-30 22:54 UTC, ibooker approved these changes

2023-09-06 15:03 UTC, merged